name: Nuget CI

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/* ]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: setup .net core sdk
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version:  6.*

            - name: dotnet build
              run: dotnet build RulesEngineEditor.sln --configuration Release

            - name: dotnet pack
              run: dotnet pack RulesEngineEditor.sln -c Release --no-build --include-source --include-symbols

            - name: setup nuget
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: NuGet/setup-nuget@v1.0.6
              env:
                  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
              with:
                  nuget-version: latest

            - name: Publish NuGet
              uses: brandedoutcast/publish-nuget@v2
              with:
                PROJECT_FILE_PATH: src/RulesEngineEditor/RulesEngineEditor.csproj # Relative to repository root
                NUGET_KEY: ${{ secrets.NUGET_API_KEY }} 
                PACKAGE_NAME: RulesEngineEditor
